POST {{host}}/student
{
  "name": "Ajay",
  "rollNo": "12BB01",
  "class": "12",
  "section": "B"
}
HTTP 200


POST {{host}}/student
{
  "name": "Arjun",
  "rollNo": "12BB02",
  "class": "12",
  "section": "B"
}
HTTP 200

POST {{host}}/student
{
  "name": "Aryan",
  "rollNo": "12BB03",
  "class": "12",
  "section": "B"
}
HTTP 200

POST {{host}}/student
{
  "name": "Arvind",
  "rollNo": "12BB04",
  "class": "12",
  "section": "B"
}
HTTP 200

POST {{host}}/student
{
  "name": "Arijit",
  "rollNo": "12BB05",
  "class": "12",
  "section": "B"
}
HTTP 200